from SUMI import DEMONS, DEV_USERS, DRAGONS, TIGERS, WOLVES, telethn

ISHIKKI = [5030730429]

IMMUNE_USERS = DRAGONS + WOLVES + DEMONS + TIGERS + DEV_USERS + ISHIKKI

IMMUNE_USERS = (
    list(DRAGONS)
    + list(WOLVES)
    + list(DEMONS)
    + list(TIGERS)
    + list(DEV_USERS)
    + list(ISHIKKI)
)
